# Created by kryg at 6/20/16
Feature: CreateProjects

  Scenario: Create
    Given Visit the url "https://testing.alytics.ru/"
      When Fill "#req1" with "vskr@alytics-team.com"
      When Fill "#req2" with "314159265"
      And Click "[type=submit]"
      And Click the button ".add-project-button"
      And Fill "#project-input-0" with "it_project"
      And Fill "#project-input-1" with "it_project.com"
      And Click the button ".submit-form"
      And Wait disappearance ".progress-bar"
      And Fill "#project-input-0" with "alytics3"
      And Click the button ".submit-form"
      And Switch to new window opened
#      And Click the button "[name='project[yandex_client]']"
#      And Wait appearance "[name='project[yandex_client]']"
#      And Wait disappearance ".progress-bar"
#      And Click "[name='project[yandex_client]']:first-of-type"
#      And Click the button ".submit-form"
      And Fill "#login" with "alytics3"
      And Fill "#passwd" with "it_project"
      And Click ".domik-submit-button"
      And Wait disappearance ".progress-bar"
      And Click ".all-campaigns"
      And Click the button ".submit-form"
      And Wait disappearance ".progress-bar"
      And Click the button ".submit-form"
      And Wait disappearance ".progress-bar"
      And Click ".js-profile-value:first-of-type"
      And Click the button ".submit-form"
      And Wait disappearance ".progress-bar"
      And Wait appearance ".submit-form:not([disabled])"
      And Click the button ".submit-form"
      And Wait disappearance ".progress-bar"
      And Click the button ".submit-form"
      And Wait disappearance ".progress-bar"
      And Wait appearance "[name=utm_medium]"